# Put this file under:
# /usr/local/openresty/nginx/conf/conf.d/zz_dqueryd_support.conf
# It is expected to be included from the global http {} context.

map $http_cf_connecting_ip $dquery_client_ip {
    default $http_cf_connecting_ip;
    ""      $remote_addr;
}

upstream dqueryd_backend {
    server 127.0.0.1:18053;
    keepalive 32;
}
